---
- name: install core nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0664

- name: install site nginx config
  template:
    src: jhaines.conf.j2
    dest: /etc/nginx/conf.d/jhaines.conf
    mode: 0664

- name: synchronize static content files
  synchronize:
    src: "{{ playbook_dir }}/../../dist/"
    dest: "/var/www/jhain.es/"
